### ISSUE TITLE
Unable to login using google authentication

### ISSUE THREAD

**Issue by mrvamsidhar** [Azure/azure-mobile-services-cordova#24] opened 2016-03-18 14:52 UTC
I just started using this plugin. I was able to login using google authentication  on chrome browser in my desktop.  But, When I install in device and try to login using using google authentication I am getting below.
Here is my code. I installed below plugins

```
 <plugin name="cordova-plugin-whitelist" version="1.2.1" />
  <plugin name="com.microsoft.azure-mobile-services" version="1.2.9" />
  <plugin name="cordova-plugin-inappbrowser" version="1.3.0" />
  <plugin name="cordova-plugin-device" version="1.1.1" />
```

```
  mobileService = new WindowsAzure.MobileServiceClient(
              "https://test.azure-mobile.net/",
              "XXXXXXXXXXXXXXXXXXXXXX"
          );
            mobileService.login('google').then(function (result) {
                console.log('success - result',result);              

            }, function (error) {
                console.log(error);
            });`

```

![screenshot_2016-03-18-20-16-32 1](https://cloud.githubusercontent.com/assets/3186542/13881311/73f42a84-ed46-11e5-8e7d-1086814e30d9.png)

**Comment by shrishrirang** [comment] 2016-03-19 00:11
I have responded to your query on https://social.msdn.microsoft.com/Forums/en-US/20a4931f-459d-4727-a4d2-b2d9baa4f2fb/azure-mobile-services-cordova-plugin-issue-unable-to-login-using-google-authentication. I am closing this issue as this is a duplicate of that query.

**Closed as completed by shrishrirang** 2016-03-19 00:11 UTC
